# Generated by Django 3.2.6 on 2021-08-06 03:25

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210805_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', verbose_name='Service slug')),
                ('image', models.ImageField(default='default-picture.png', upload_to='services/')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Service Articles',
            },
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'Service'},
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicearticle', verbose_name='Service'),
        ),
    ]
