# Generated by Django 3.2.6 on 2021-08-06 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210805_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearticle',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, verbose_name='Service slug'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicearticle', verbose_name='Article'),
        ),
    ]
