# Generated by Django 3.2.6 on 2021-08-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210805_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearticle',
            name='slug',
            field=models.SlugField(default='', max_length=100, verbose_name='Service slug'),
        ),
    ]
