# Generated by Django 3.2.6 on 2021-08-06 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicearticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearticle',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, unique=True, verbose_name='Service slug'),
        ),
        migrations.CreateModel(
            name='WorkPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subparagraphs', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicearticle', verbose_name='What will we do:')),
            ],
        ),
    ]
