# Generated by Django 3.2.6 on 2021-08-06 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_workpoint_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpoint',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpoints', to='services.servicearticle', verbose_name='What will we do:'),
        ),
    ]
