# Generated by Django 3.2.6 on 2021-08-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_workpoint_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workpoint',
            old_name='subparagraphs',
            new_name='text',
        ),
    ]
