# Generated by Django 3.2.6 on 2021-08-06 23:02

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rename_subparagraphs_workpoint_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpoint',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
