# Generated by Django 3.2.6 on 2021-08-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rename_subparagraphs_workpoint_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, verbose_name='Category slug'),
        ),
    ]
