# Generated by Django 3.2.6 on 2021-08-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_workpoint_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpoint',
            name='text',
            field=models.TextField(),
        ),
    ]
