# Generated by Django 3.2.6 on 2021-08-10 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicecategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='services.servicearticle', verbose_name='Article'),
        ),
    ]
