# Generated by Django 3.2.6 on 2021-08-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_servicecategory_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearticle',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicearticle',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicearticle',
            name='text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicearticle',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicearticle',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicearticle',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
