# Generated by Django 3.2.6 on 2021-08-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_servicearticle_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearticle',
            name='text',
            field=models.TextField(),
        ),
    ]
