# Generated by Django 3.2.6 on 2021-09-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20210812_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearticle',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='servicearticle',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='servicearticle',
            name='text_uk',
        ),
        migrations.RemoveField(
            model_name='servicearticle',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='servicearticle',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='servicearticle',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='workpoint',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='workpoint',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='workpoint',
            name='text_uk',
        ),
        migrations.RemoveField(
            model_name='workpoint',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='workpoint',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='workpoint',
            name='title_uk',
        ),
    ]
