# Generated by Django 3.2.6 on 2021-10-06 10:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20210915_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearticle',
            name='text',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='servicearticle',
            name='text_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='servicearticle',
            name='text_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='servicearticle',
            name='text_uk',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
