# Generated by Django 3.2.6 on 2021-10-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20211006_1022'),
        ('services', '0018_auto_20211006_1559'),
    ]

    operations = [
    ]
