# Generated by Django 3.2.6 on 2021-08-12 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='employees.employee'),
        ),
    ]
