# Generated by Django 3.2.6 on 2021-09-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_skill_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='social_logos/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='employees.socialaccount')),
            ],
        ),
    ]
