# Generated by Django 3.2.6 on 2021-09-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_socialaccount_socialnetworks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialNetworks',
            new_name='SocialNetwork',
        ),
    ]
