version: '3'

services:

  backend:
    build: src
    container_name: diploma_container
    restart: always
    command: ./commands/start_server_${MODE}.sh
    ports:
      - "${PORT}:${WSGI_PORT}"
    volumes:
      - .\src:/srv/project/src
      - .\commands:/srv/project/commands
      - .\src\media:/srv/project/media
      - static_content:/var/www/ArtAds
    env_file:
      - src/.env
    environment:
      - DJANGO_SETTINGS_MODULE=ArtAds.settings.${MODE}

#  postgres:
#    image: postgres:12
##    environment:
##      - POSTGRES_PASSWORD=mysecretpassword
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    env_file:
#      - .env

  nginx:
    image: nginx:1.19
    volumes:
      - .\nginx:/etc/nginx/conf.d
      - static_content:/var/www/ArtAds
    ports:
      - 80:80
      - 443:443
    env_file:
      - src/.env
    depends_on:
      - backend

volumes:
  pg_data: {}
  static_content: {}