# Generated by Django 3.2.6 on 2021-08-07 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', tinymce.models.HTMLField(null=True)),
                ('quota', models.TextField()),
                ('publish_date', models.DateField(auto_now=True)),
                ('page_views', models.IntegerField(default=0, editable=False)),
                ('rating', models.IntegerField(default=0, editable=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
