# Generated by Django 3.2.6 on 2021-08-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default-picture.png', null=True, upload_to='articles/'),
        ),
    ]
