# Generated by Django 3.2.6 on 2021-08-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, unique=True),
        ),
    ]
