# Generated by Django 3.2.6 on 2021-08-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='quota',
            new_name='quote',
        ),
    ]
