# Generated by Django 3.2.6 on 2021-08-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Moderation'), (1, 'Published'), (2, 'Archived')], default=0),
        ),
    ]
