# Generated by Django 3.2.6 on 2021-08-10 00:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_comment_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='text_after_quote',
        ),
        migrations.AddField(
            model_name='article',
            name='text_before_quote',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
