# Generated by Django 3.2.6 on 2021-08-10 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rename_subparagraphs_workpoint_text'),
        ('articles', '0010_auto_20210810_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
