# Generated by Django 3.2.6 on 2021-08-11 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
        migrations.CreateModel(
            name='ArticleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_rating', to='articles.article')),
            ],
        ),
    ]
