# Generated by Django 3.2.6 on 2021-08-12 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='quote_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='quote_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='quote_uk',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_after_quote_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_after_quote_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_after_quote_uk',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_before_quote_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_before_quote_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_before_quote_uk',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_uk',
        ),
    ]
