# Generated by Django 3.2.6 on 2021-08-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20210812_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quote_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='quote_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='quote_uk',
            field=models.TextField(null=True),
        ),
    ]
