# Generated by Django 3.2.6 on 2021-08-12 03:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20210812_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_after_quote_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_after_quote_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_after_quote_uk',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_before_quote_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_before_quote_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_before_quote_uk',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
