# Generated by Django 3.2.6 on 2021-08-13 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20210812_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, editable=False, max_length=100, unique=True),
        ),
    ]
