# Generated by Django 3.2.6 on 2021-08-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='full_image',
            field=models.ImageField(default='default-picture.png', upload_to='cases'),
        ),
        migrations.AddField(
            model_name='case',
            name='mob_image',
            field=models.ImageField(default='phone.png', upload_to='cases'),
        ),
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.category', verbose_name='Category'),
        ),
    ]
