# Generated by Django 3.2.6 on 2021-08-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20210805_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='case',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
